appium/appium-base-driver

lib/commands/session.js
@jlipps moiz and I did this so that multiple sessions can run on a single android driver. `opts` wasn't getting reset on session delete.
Interesting thing here: when running androidDriver standalone, multiple sessions reuse a single driver object. In the main Appium module, each session is assigned to a single object, and a new one is created for each session. Do we want to rewrite the standalone server in androidDriver so that it creates new AndroidDrivers when sessions are created?
=> delete opts when session is deleted

lib/desired-caps.js, test/capability-specs.js
Our old behaviour was to allow boolean caps to be sent as strings (e.g., `"false"` being the same as `false` as a cap value). Continue that tradition.
=> Allow booleans to be strings

lib/desired-caps.js
Otherwise we get log messages saying they are not understood, though they are.
=> Add language and locale to desired capabilities

lib/commands/session.js, lib/helpers.js, test/capability-specs.js
We previously fixed the caps before sending them to the sub-driver. This caused problems because caps that were not supposed to be boolean, but _were_ strings with the value `"true"` or `"false"` would be converted. This particularly happened with iOS's `waitForAppScript`.
To fix this, here we parse the cap constraints to get the ones that are supposed to be booleans, before doing the transformation. This needs to be done in the driver.
=> Move fix caps function from appium driver

lib/express/server.js, test/basedriver/driver-e2e-tests.js, test/express/server-specs.js
We have cases (notably within the xcuitest driver) where we get odd results because the server is not closing correctly.
This is backwards compatible, in that an un-awaited promise behaves the same as a function that takes a callback but ignores that callback.
=> Make sure the server is closed when we call close

lib/basedriver/desired-caps.js
We are using `XCUITest` instead of `WebDriverAgent` as the `automationName`.
=> Change name of xcuitest automation name

lib/basedriver/commands/timeout.js, lib/basedriver/driver.js
Fix a problem where a command method is not `async`, and add a little logging for valid locator strategies.
=> Make sure async is there, and add logging

lib/basedriver/commands/timeout.js, lib/basedriver/driver.js, test/basedriver/timeout-specs.js
We are getting in the situation where we need to have drivers that manage other drivers (e.g., `appium-xcuitest-driver` has an instance of `appium-safari-driver` that it delegates webbish stuff too). Rather than _ad hoc_ management of these drivers, let's move it into the base driver. 
At the moment only timeouts need to be handled.
=> Add ability to manage delegated drivers

lib/mjsonwp/routes.js, test/mjsonwp/routes-specs.js
We will, eventually, need to support the new spec, while also supporting the old versions until all the clients are updated. Keep track of that here.
=> Begin adding W3C route alternatives

lib/basedriver/driver.js, test/basedriver/driver-tests.js
Certain clients (like the java client) poll the server to make sure things are ok. The main Appium driver implements a `getStatus` method that returns build information, but if someone is testing against a specific driver their tests cannot even get past the client trying to connect.
=> Add basic getStatus method

lib/mjsonwp/mjsonwp.js
Added condition in [`mjsonwp.js`](https://github.com/sravanmedarapu/appium-base-driver/blob/master/lib/mjsonwp/mjsonwp.js#L257) to return executed command status (i.e. [`driverRes`](https://github.com/sravanmedarapu/appium-base-driver/blob/master/lib/mjsonwp/mjsonwp.js#L267)) as response if driver is [`UiAutomator2Driver`](https://github.com/sravanmedarapu/appium-base-driver/blob/master/lib/mjsonwp/mjsonwp.js#L249) type.
Issue: https://github.com/appium/appium-uiautomator2-driver/issues/27
=> Refactored mjsonwp with respect to UiAutomator2Driver functionality

lib/express/static.js
Allow the delay to be specified in either the body or the query params.
=> Allow guinea pig delay to be in query

.gitignore, lib/mjsonwp/routes.js, test/mjsonwp/routes-specs.js
requires : [adding fingerprint command](https://github.com/appium/appium-android-driver/pull/181) to work.
=> adding fingerprint to routes

package.json
currently using version 2.x.x not able to parse ProxyRequestError's error json object to readable format.
=> Updated request-promise version to 4.1.1

lib/jsonwp-proxy/proxy.js
xcuitest real devices work significantly better if the connection is not closed on each request. Other systems seem to work fine in keep-alive mode, too.
=> Use keep-alive connection for proxying

lib/mjsonwp/routes.js, test/mjsonwp/routes-specs.js
There are some third-party libraries that send in "capabilities" (with desired and required capabilities inside) as well as the desired and required capabilities. Appium doesn't like this. None of our drivers use this object, but it should be allowed,
=> Add capabilities to create session

lib/basedriver/driver.js
`os.tmpDir` is deprecated in Node 7.
=> Make use of os.tmpdir instead of os.tmpDir

lib/basedriver/helpers.js
Addresses https://github.com/appium/appium-base-driver/issues/79
Sometimes you can't tell the file type from a URL. Like URL minimizers or if there are parameters, etc. So just check the content type of the response. If it's a zip file, ensure it gets unzipped in subsequent logic. Otherwise, assume it's an app file.
Works on:
- URL pointing to an APK file
- URL pointing to a ZIP file
- URL pointing to a ZIP file but with parameters in the URL
Note: The `downloadApp` and `downloadFile` functions are exported in helpers. Their signatures have changed. But I did a full grep on all the code from a fresh Appium node install (including node_modules) and saw the only users were inside `helpers.js` so I don't think this is would break anyone.
=> Handle zip files from URLs

lib/jsonwp-proxy/proxy.js, lib/mjsonwp/mjsonwp.js
Removing _truncate for requests for better debugging
All the proxied requests are logged truncated in log files. It's hard to identify what was the original request which failed.
=> Removing _truncate for requests for better debugging

docs/mjsonwp/protocol-methods.md, lib/mjsonwp/routes.js, test/mjsonwp/routes-specs.js
For: https://github.com/appium/appium-android-driver/pull/192
It seems a lot of clients have to be updated to support these out of the box. I wasn't able to do `driver.execute('display_density')` in Python because the Appium client uses the Selenium client which does a look up in a table of predefined commands. I assume clients for all the other languages are the same.
Work around to get functionality is to build a URL and make a request without using a client, which is how I tested this.
=> Add routes and docs for device commands

lib/mjsonwp/mjsonwp.js, test/mjsonwp/routes-specs.js
Check before adding `sessionId` and `id` to the optional parameters. Otherwise, after a number of sessions, we end up with things like:
```
dbug MJSONWP Calling XCUITestDriver.createSession() with args: [{"safariIgnoreFraudWarning":false,"safariInitialUrl":"http://0.0.0.0:4994/test/guinea-pig","safariAllowPopups":true,"nativeWebTap":true,"browserName":"Safari","platformName":"iOS","platformVersion":"9.3","deviceName":"iPhone 6","automationName":"XCUITest","noReset":true},null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
```
=> Do not keep adding sessionId and id to optional parameters

lib/express/middleware.js, lib/express/server.js, test/express/server-specs.js, test/mjsonwp/mjsonwp-specs.js
The webdriver spec specifies that requests where the method is POST
should be parsed as JSON (see https://www.w3.org/TR/webdriver/#processing-model step 6).
Appium is too restrictive. It only parses as JSON if the application/json
Content-Type is provided, making it incompatible with some Webdriver clients
that follow the spec but don't send a Content-Type header.
This commit makes Appium less restrictive by defaulting to the application/json
Content-Type if none is provided.
=> Default to application/json when no Content-Type is supplied

lib/mjsonwp/routes.js, test/mjsonwp/routes-specs.js
To get performance data via https://github.com/appium/java-client/pull/562 , this driver should apply parameters `packageName`, `dataType` and `dataReadTimeout `, not `applicationPackageName` and  `performanceDataType`, I think.
The following log is sending parameters with  `packageName`, `dataType` and `dataReadTimeout`. If I sent parameters with `applicationPackageName` and `performanceDataType`, then Appium return `{}` as the result.
What do you think? @heeseon 
```
[HTTP] --> POST /wd/hub/session/b3250db7-4d90-4e52-b0bb-989940cb08ae/appium/getPerformanceData {"packageName":"io.appium.android.apis","dataType":"cpuinfo","dataReadTimeout":1000}
[debug] [MJSONWP] Calling AppiumDriver.getPerformanceData() with args: ["io.appium.android.apis","cpuinfo",1000,null,null,"b3250db7-4d90-4e52-b0bb …
```
=> update required an optional parameters for getting performance

lib/jsonwp-proxy/proxy.js
This PR has the same reason as https://github.com/appium/appium-xcuitest-driver/pull/432
After further investigation I realised that only this place of code could throw such type of errors.
=> Add warning message for erroneous responses to make debugging easier

lib/mjsonwp/routes.js, test/mjsonwp/routes-specs.js
`appium` vendor route for getting the current package, mirroring the getting of the current activity, which is already available.
First step in https://github.com/appium/appium/issues/5493
=> Add route to get current package

lib/basedriver/helpers.js, test/basedriver/helpers-e2e-specs.js
When downloading an app, use the URL's pathname rather than the whole URL to determine if it needs to be unzipped.
Fixes https://github.com/appium/appium/issues/8793
=> Allow downloaded app urls to have query strings

lib/basedriver/driver.js
session should be closed firstly if some unexpected happens, so the following request can be responsed immediately.
=> exchange deleteSession and curCommandCancellable

static/test/guinea-pig-scrollable.html, static/test/guinea-pig.html, static/test/guinea-pig3.html, static/test/guinea-pig4.html, static/test/guinea-pig5.html
We have tests that rely on distinguishing between what links we tap, but most of the links actually open the same page. So change that, so each link opens a distinct page.
This will be a breaking change, unfortunately, since tests that rely on the old behavior will fail unexpectedly with the text they are searching for having been changed.
=> Make different pages and links distinguishable

lib/basedriver/driver.js
It is better to have this property defined in the base class to avoid the exception thrown by `curSessionDataForDriver` AppiumDriver's method. This error prevents parallel driver instances to be created.
=> Add driverData property to the base driver class

lib/basedriver/driver.js
This is a "blind" implementation of the feature that we discussed before. I didn't test it with a real client, but it's just how I see it should look like. The next step will be to override _isCommandsQueueEnabled_ property in AppiumDriver to make it return false :)
=> Add a possibility to execute commands without queueing them

lib/jsonwp-proxy/proxy.js, test/jsonwp-proxy/proxy-specs.js
Whenever I executed androidDriver.closeApp() and androidDriver.launchApp() for my hybrid app, I had the situation that Appium did not detect that a new chrome driver connection has to be established. I received then the error message "chrome not reachable". This can be fixed by checking the response body status code: resBody should only be returned as a whole, when there was no resonse body status code defined in the response.
=> Detect a non-working chromedriver connection after androidDriver.closeApp() and androidDriver.launchApp()

lib/basedriver/capabilities.js, lib/basedriver/driver.js, lib/mjsonwp/errors.js, lib/mjsonwp/mjsonwp.js, package.json, test/basedriver/capabilities-specs.js, test/basedriver/driver-tests.js, test/mjsonwp/errors-specs.js, test/mjsonwp/fake-driver.js, test/mjsonwp/mjsonwp-e2e-specs.js
* Remembers protocol requested in createSession
* Checks the parameters in 'createSession' and determines if it's W3C or MJSONWP
* MJSONWP expects `{desiredCapabilities: {...}`; W3C expects `{capabilities: {alwaysMatch: {...}, firstMatch: [{...}, ...]}`
* Also renamed 'processCaps' to 'processCapabilities'
* Add W3C error format
* Add W3C status codes to errors
* When deciding error format to return in mjsonwp.js, check format and then return eitherJSONWP or W3C format
(related to https://github.com/appium/appium/issues/9574)
=> W3C Error Formatting

lib/mjsonwp/validators.js, test/mjsonwp/validator-specs.js
The main reason for this pull request was to fix the URI scheme validator, to ensure dot and plus characters are recognised as allowed, in line with [rfc 2396](http://www.ietf.org/rfc/rfc2396.txt).
In running the tests for this, it seemed that `.should.not.throw` in the validator specs was not actually checking anything and was always passing even if something was thrown, and instead should be `.should.not.throw()`, so I've changed that too.
=> Allow dot and plus character in valid uri scheme

index.js, lib/basedriver/capabilities.js, test/basedriver/capabilities-specs.js
* Strip out 'appium:' prefixes
* Reject standard capabilities that contain the 'appium:' prefix
* Expose 'processCapabilities' as API method
(see https://www.w3.org/TR/webdriver/#dfn-extension-capabilities for reference)
(related to https://github.com/appium/appium/issues/9785)
=> Handle capabilities prefixes

lib/mjsonwp/routes.js, test/mjsonwp/routes-specs.js
The new W3C-compatible endpoint is only available since Selenium 3.8.0 (which is currently not supported even by beta version of java client), although I think it costs nothing for us to support the legacy endpoint as well.
=> Support pre-W3C element screenshot endpoint

lib/basedriver/commands/find.js, lib/basedriver/desired-caps.js
Add a capability `printPageSourceOnFindFailure` that, when on, makes the server print the page source at the point of find element failure. We find that quite often when people are having problems with finding elements, the first step is to ask them to check the page source to see if the element is there, and if it has the correct id/class/path/whatever. This makes that easier to accomplish.
=> Add printPageSourceOnFindFailure flag to print source when find fails

lib/basedriver/capabilities.js
* Appium logs warnings about W3C caps that aren't prefixed with `appium:`
* Was incorrectly warning about prefixed caps.
* Fix makes it so it warns about unprefixed, non-standard caps.
=> Fix incorrect identifying of unprefixed caps

lib/basedriver/capabilities.js, test/basedriver/capabilities-specs.js
* Doesn't make sense to validate 'presence' in the firstMatch caps, because the firstMatch caps extend alwaysMatch and is going to miss necessary capabilities
* Only 'alwaysMatch' should validate 'presence'
* Simply set the 'skipPresenceConstraint' in 'validateCaps' to true for firstMatch caps
=> Don't validate 'presence' on firstMatch caps

lib/mjsonwp/mjsonwp.js, test/basedriver/driver-tests.js, test/mjsonwp/fake-driver.js
Also:
* Make the 'fake-driver' a MJSONWP driver
* Fix unit tests that were broken when being called in 'appium-fake-driver'
=> Make it so that 'status' is only returned for MJSONWP

lib/mjsonwp/mjsonwp.js, test/mjsonwp/mjsonwp-e2e-specs.js
* Make it return format like this: https://github.com/jlipps/simple-wd-spec#new-session
```javascript
{
"capabilities": {
...
},
"sessionId": "<SESSION_ID>"
}
```
=> w3c CreateSession response

lib/basedriver/helpers.js
The current code leaves too many file leftovers behind if the downloaded stuff requires unzipping or some failure happens during the extraction process.
=> Make sure that temporary files are cleaned up properly while configuring the app

lib/mjsonwp/routes.js, test/mjsonwp/routes-specs.js
related: https://github.com/appium/ruby_lib/issues/739
Getting active elements is `GET` method for the W3C protocol.
=> add getting active element for w3c

lib/basedriver/automation-names.js, lib/basedriver/automations.js, lib/basedriver/desired-caps.js, lib/basedriver/driver.js, test/basedriver/capabilities-specs.js, test/mjsonwp/mjsonwp-e2e-specs.js
* Made an 'automations.js' file that lists all valid automations as an Object instead of hard-coding it
* Make desired-caps pull in the values of those automations for validation instead of hard-coding them
* Expose 'validAutomations' to Driver object
* appium/appium will use this instead of hardcoding automation names to avoid possible errors
=> Set automations in one file

lib/basedriver/commands/timeout.js, lib/mjsonwp/mjsonwp.js, lib/mjsonwp/routes.js, lib/mjsonwp/validators.js, package-lock.json, test/basedriver/driver-tests.js, test/basedriver/timeout-specs.js, test/mjsonwp/routes-specs.js, test/mjsonwp/validator-specs.js
According to [the W3C spec](https://github.com/jlipps/simple-wd-spec#set-timeouts), clients send `{implicit: 3000}` as request body to the server. But current implementation expects `{type: implicit, ms: 3000}` for both W3C and MJSONWP.
I've changed to `optional` parameter because of supporting both W3C format and MJSONWP one.
https://github.com/appium/appium-base-driver/compare/master...KazuCocoa:fix_timeout_for_w3c?expand=1#diff-28707e6fe74fc702b56e27eaff233df0R25
Ideally, I'd like to remain `required: ['type', 'ms']}` for MJSONWP and set `optional: ['script', 'pageLoad', 'implicit']` for W3C, but I didn't come up with good idea... Do you have any good way to implement this?
```
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: …
```
=> Fix implicit wait for w3c

lib/basedriver/capabilities.js, lib/mjsonwp/errors.js, lib/mjsonwp/mjsonwp.js, test/mjsonwp/mjsonwp-e2e-specs.js
* Make malformed caps return 400 error  
* Add InvalidArgumentTypeError to errors
* Made 'NotYetImplementedError' a 405 (Method Not Allowed) status code
* Made errors in 'createSession' return InvalidArgumentTypeError when capabilities are invalid or malformed
* Fix incorrect W3C responses 
* Add w3c status for NotImplemented and NotYetImplemented
* Changed `getResponseForW3CStatusError` so that it throws an unknown error if the exception isn't a w3c exception
* Checks for property `.w3cStatus` on the Error to confirm if it's a proper W3C protocol-blessed exception (@jlipps do you think this is adequate?)
* Moved logic that reassigned errors into MJSONWP conditional blocks; W3C shouldn't reassign errors because they all have their own specific HTTP status codes
* Added endpoint tests that …
=> Fix problems with W3C responses

lib/mjsonwp/routes.js, test/mjsonwp/routes-specs.js
iOS and Android have different of configurable options for screen recording, so that the previous implementation is not cross platform.
=> Update parameters list for start_recording_screen/stop_recording_screen endpoints

lib/basedriver/commands/session.js, test/basedriver/capability-specs.js
* If 'capabilities' and 'desiredCapabilities' were provided, and 'capabilities' is NOT a plain object, fall back to 'desiredCapabilities'
* Added more logging to the W3C vs. MJSONWP determination logic
* Rename `createSession` args to be more descriptive
* Added basic W3C unit tests for above fix
=> Check that W3C capabilities is a plain object

lib/basedriver/capabilities.js, test/basedriver/capabilities-specs.js
* Previously, it was going through alwaysMatch and all of the firstMatch caps and individually logging when any of them had unprefixed, non-standard caps
* Now it does them all at once
* Made a helper function that takes a caps object ({alwaysMatch, firstMatch}) and finds all of the non-prefixed caps in all of them
* Calls that function and logs warning
=> Consolidate non-prefixed caps warnings

lib/basedriver/helpers.js, lib/mjsonwp/mjsonwp.js, test/basedriver/helpers-specs.js, test/mjsonwp/mjsonwp-e2e-specs.js
* If server encounters a response that has the wrong key name (if it's a W3C session and ELEMENT is provided when it should be 'element-6066-11e4-a52e-4f735466cecf'), rename all instances of that key
* Added a helper method `renameKey` that recursively finds instances of a 'key' and renames it
* Added unit tests for `renameKey`
* Added e2e test that mocks `findElements`, calls `/elements` endpoint and verifies that the payload was correctly renamed
=> Rename ELEMENT key to W3C format

lib/mjsonwp/errors.js, lib/mjsonwp/mjsonwp.js, test/mjsonwp/errors-specs.js, test/mjsonwp/mjsonwp-e2e-specs.js
* Refactored `getResponseForW3CError` to return proper response 
* Changed method so that it returns `{value: {stacktrace: '...', message: '...', error: '...'}}` (a la https://github.com/jlipps/simple-wd-spec#error-handling)
* `message` is the same as the JSONWP error message
* `error` is a static message indicating the type of error
* `stacktrace` is the callstack provided in the error
* Added an attribute called `error` to all of the MJSONWPErrors in `errors.js` which contains the static description of the W3C error
* Also made `getResponseForW3CError` handle BadParametersError
* `BadParametersError` isn't an `MJSONWPError` so it needs to be handled differently
* Refactored `getResponseForW3CError` and `getResponseForJsonwpError` into errors.js file
(connected to …
=> Add W3C Error Response

lib/mjsonwp/routes.js, test/mjsonwp/routes-specs.js
I'd like to generalise this application management interface for both Android and iOS (XCUITest) and deprecate the corresponding `mobile:` helpers in the next major driver version.
Related to https://github.com/appium/appium-android-driver/pull/300
=> Tune application management endpoints

index.js, lib/jsonwp-proxy/proxy.js, lib/protocol/errors.js, lib/protocol/index.js, lib/protocol/protocol.js, test/protocol/errors-specs.js, test/protocol/protocol-e2e-specs.js
* Rename '.error' property to correct W3C property
* The error property in the ProtocolError objects should match up with https://www.w3.org/TR/webdriver/#handling-errors under the 'JSON Error Code' column
* Did this and added tests for all of these
* Add proxying for W3C responses 
* If a W3C Response is provided by a proxy, map to the correct error
* Checks if `value` is an object and `value.error` and maps it based on that (`value.error` is the W3C error code)
* Broke off `errorFromCode` into `errorFromMJSONWPStatusCode` and `errorFromW3CJsonCode`
=> Fixed W3C error messaging

index.js
* When doing refactoring, erroFromCode was split into 'errorFromMJSONWPStatusCode' and 'errorFromW3CJsonCode'
* 'errorFromCode' was being exported as an alias for 'errorFromW3CJSONCode' to avoid breaking changes
* Should have been an alias for 'errorFromMJSONWPStatusCode' though
(fixes this issuehttps://circleci.com/gh/appium/appium-xcuitest-driver/1617?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
The unit test sure saved me on this one
=> Reassign 'errorFromCode' to 'errorFromW3CJSONCode'

lib/protocol/errors.js, test/protocol/errors-specs.js
* Previously if the proxy error was a string it assumed it was jsonwp and parsed it
* Now it parses the responseError and then does it's normal business
* Added tests to `errors-specs.js` that have the fix (the `W3C --> should parse a JSON string` test failed before the fxi was put in)
=> Parse strings for W3C and JSON

lib/protocol/routes.js, test/protocol/routes-specs.js
Unfortunately java client does not support sending parameters in get requests, so I must change it to POST
=> Change the request type of queryAppState to POST

lib/basedriver/helpers.js
This addresses https://github.com/appium/appium/issues/3439
The idea is to compare the actual date returned by file server in Last-Modified header and to reuse the already downloaded application if the current date is less or equal to the cached one
=> Add urls caching logic

lib/protocol/protocol.js
Default value of payload parameters is an array(`[]`). However, as long as I saw the implementation of `makeArgs`, it seems to expect an object. So I think `{}` is correct for the default value. `[]` is working because an array is also an object in JavaScript, tho.
=> Fix the default value of payload parameters

lib/basedriver/commands/index.js, lib/basedriver/commands/log.js, test/basedriver/commands/log-specs.js
Implement https://github.com/appium/appium-ios-driver/pull/267 and https://github.com/appium/appium-android-driver/pull/338/files in the base driver. The subclasses ought to just remove their implementations of `getLogTypes` and `getLog`, and make sure there is a `supportedLogTypes` property with the correct log types for that instance.
=> Add logging commands to the base driver

lib/protocol/errors.js, test/protocol/errors-specs.js
It looks like we should always use the spec at https://w3c.github.io/webdriver/webdriver-spec.html, which is up to date. See https://github.com/SeleniumHQ/selenium/issues/5562 for more details.
=> Sync w3c codes with the recent spec

lib/basedriver/commands/session.js, lib/basedriver/driver.js, test/basedriver/driver-tests.js, test/protocol/protocol-e2e-specs.js
* Previously, we were only checking the HTTP payload to see what protocol should be
* This is inadequate, in the case of drivers that don't proxy W3C Capabilities yet
* The fix now is to set the protocol in `createSession` to see if the W3C caps were proxied through, if they're not, set protocol to MJSONWP
* Added unit test and one e2e test to confirm that this works
(related to: https://github.com/appium/appium/issues/10350)
=> Fix: Determine protocol in createSession

index.js, lib/express/websocket.js, test/basedriver/websockets-e2e-specs.js
The previous implementation was too implicit and not very obvious.
=> Tune prefix handling for web socket pathnames

lib/protocol/protocol.js, test/basedriver/driver-e2e-tests.js
(look at this PR first: https://github.com/appium/appium/pull/10362)
* If `executeCommand` returns an object that has a property 'protocol' and either a 'value' property or an 'error' property, adjust the response so that we respond with the protocol that the `executeCommand` function told us to use for the response
* Also: Added to delay in the 'unexpected exits' test because I was getting a race condition
=> Parse protocol from executeCommand

lib/protocol/protocol.js, test/protocol/protocol-specs.js
* Some problems with parsing `{protocol: <protocol>, value: <value>}`
* `(!_.isNil(driverRes.value)` was incorrect check because `value` can be undefined or null; replaced it with `_.has(driverRes, 'value')` to check that the `value` property was set
*  ```
if (driverRes.value) {
driverRes = driverRes.value;
} 
``` 
was also incorrect because `driverRes.value` may be false-y
* Moved logic into it's own function and then added tests to cover the problem cases
=> Fix protocol parsing

lib/basedriver/helpers.js, lib/express/middleware.js, lib/express/static.js, lib/jsonwp-proxy/proxy.js, test/basedriver/helpers-e2e-specs.js, test/express/server-specs.js, test/jsonwp-proxy/mock-request.js, test/jsonwp-proxy/proxy-specs.js
This should resolve issues like appium/ruby_lib#598 (comment), since some HTTP servers fall back to ASCII instead of UTF-8 if the content encoding is not set explicitly in request headers.
@KazuCocoa FYI
=> Enforce UTF-8 encoding on request headers

lib/jsonwp-proxy/proxy.js, test/jsonwp-proxy/proxy-specs.js
This method should throw specialised errors instead of the generic one. Also, it supports W3C responses now.
See https://github.com/appium/appium-xcuitest-driver/pull/688#issuecomment-395065421 for more details.
Also, it looks like WDA always returns returns response code as 200 independently of the actual response status.
=> Fix sending of commands by JWProxy  class

lib/basedriver/driver.js, test/basedriver/driver-tests.js
* Before, it was creating a new session and using the processed caps
* Problem was, if it was W3C it would create a MJSONWP
* Now it checks the protocol before resetting and passes in the appropriate args to createSession depending on the protocol type
(related to: https://github.com/appium/appium/issues/10819)
=> 'reset' re-uses same protocol

test/basedriver/driver-tests.js
Reset tests were recently added, which do not work when the tests are imported and run in different packages (see, for instance, https://github.com/appium/appium-fake-driver/blob/master/test/driver-e2e-specs.js#L22, whose tests fail as in https://travis-ci.org/appium/appium-fake-driver/jobs/390458912#L2452).
This is because the caps constraints are changed for the different driver, and these tests don't allow for it. So just extend the caps, like the other tests.
=> Fix reset tests for importation

test/basedriver/driver-tests.js
* This test worked fine in base driver but these tests also run in fake driver and don't work beause `app ` is a required capability
* Added `app=fake` to caps
Should fix broken test: https://travis-ci.org/appium/appium-fake-driver/jobs/395675224
=> Fix: Add 'app' cap to reset tests

lib/basedriver/capabilities.js
It is more useful to see such errors in the log rather than just ignoring them
=> Log errors which happen during caps merging

lib/basedriver/commands/timeout.js, lib/jsonwp-proxy/proxy.js, test/jsonwp-proxy/proxy-specs.js, test/protocol/protocol-e2e-specs.js
* The /timeouts endpoint is a special case because the syntax differs between W3C and MJSONWP
* W3C takes a body like this:
```javascript
{pageLoad: 1, script: 2, implicit: 3}
```
* MJSONWP takes a body like this
```javascript
{type: 'script', ms: 2}
```
* Since W3C can send > 1 timeout type, we need to have special logic so that if a W3C /timeouts request is being proxied to a MJSONWP /timeouts endpoint, we need to proxy 1 request for each timeout
* The way this PR handles that is by creating an array of timeout request objects like this:
If the incoming request is W3C, like this:
```javascript
{pageLoad: 1, script: 2, implicit: 3}
```
It will generate an array that looks like this:
```javascript
[
{pageLoad: 1, script: 2, implicit: 3, type: 'pageLoad', ms: 1},
{pageLoad: 1, script: 2, …
```
=> Handle /timeouts W3C + MJSONWP proxying

lib/basedriver/desired-caps.js
The base driver should not know anything about the possible platforms that are available. That is the responsibility of the umbrella driver (see https://github.com/appium/appium/blob/master/lib/appium.js#L120-L124). Having them here both muddies that the base driver does, and also requires publishing this package in addition to the main umbrella driver when a new driver is added.
The base driver should only know that `platformName` exists, is required, and takes a string. The umbrella driver should know all the possibilities. And each individual driver should know a single possible `platformName` (e.g., `appium-ios-driver` should know only of `iOS` as a possible value).
=> Remove list of possible values for platformName cap

lib/jsonwp-proxy/proxy.js, package.json, test/jsonwp-proxy/url-specs.js
Use [lazy quantifier](https://javascript.info/regexp-greedy-and-lazy#lazy-mode) in proxy url processing, so we don't consume the whole url.
This does what #236 failed to do.
=> Fix handling of proxy url

index.js, lib/basedriver/commands/find.js, lib/basedriver/commands/images.js, lib/basedriver/device-settings.js, lib/basedriver/driver.js, lib/basedriver/image-element.js, lib/protocol/protocol.js, package.json, test/basedriver/commands/find-specs.js, test/basedriver/driver-tests.js, test/basedriver/image-element-specs.js, test/protocol/protocol-specs.js
First stab at putting the find by image logic into base driver.
I know there's no tests and docstrings, will add those. Just wanted to get the ideas here for any initial comments.
I haven't yet done extensive testing, but the happy path works for me locally.
=> add -image locator strategy and related logic

lib/protocol/protocol.js
Printing the error and then the stack trace leads to odd output. See, for instance, https://gist.github.com/saikrishna321/fa515b751d937f3c466671ec704633f9#file-latest-beta13-L152-L157.
If the message in the error is not included in the stack trace (it usually is, but not always) then append it. Otherwise the stack trace has as much information as the rest of the error does.
=> Clean up error message from protocol

lib/protocol/errors.js
Addresses https://github.com/appium/appium/issues/11245
=> Remove the redundant logging from getResponseForW3CError helper

lib/protocol/protocol.js
This exception does not always mean an error from the client perspective. That is why it would be more appropriate to log it on debug level.
=> Change logging level to debug for internal errors

lib/basedriver/commands/find.js, test/basedriver/commands/find-specs.js, test/basedriver/fixtures/custom-element-finder-bad.js, test/basedriver/fixtures/custom-element-finder.js
The idea behind this PR is to open up the possibility of "element finding plugins", which are third-party modules that users can use for element finding functionality that probably shouldn't be maintained by the core project but which nonetheless might be useful. (For example, I'm working on an experimental locator strategy involving a machine-learning model, which probably shouldn't become part of Appium core, at least not for some time).
The idea for how this should be used is as follows:
1. A third party creates a node module that exports a `find` method matching the signature described in this PR. Essentially, that third party module is passed a driver object so it can mix and match Appium capabilities with its own logic.
2. The user takes advantage of this plugin by setting the …
=> add custom locator strategy

lib/protocol/protocol.js
I'm not quite sure how it is possible that error instance does not have stack property (perhaps a node issue), but it happens: https://gist.github.com/saikrishna321/a88fd256d03e9c6ce865c632dc24b3fd
=> Avoid TypeError if stacktrace is undefined

lib/basedriver/helpers.js
I've checked all depending drivers and none of them passes more than two parameters to `configureApp` 
Also, the current implementation is not very optimal (I'm not quite sure it ever worked). It would be more effective to use smb2 library, but I don't see a purpose to implement that right now.
=> Remove samba support

lib/basedriver/helpers.js
this case was missed in the refactor, causing a regression. should definitely get something like this in before 1.10
=> allow correct downloading of zipped apps without content type header

.travis.yml, package.json
Clean out the `sudo` and `dist` portions of the Travis config, in preparation for [upcoming changes to defaults](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration) in Travis's Linux infrastructure.
=> Update dist in travis

lib/express/server.js
It turns out blindly allowing CORS could be a security hazard (who knew)
See https://github.com/w3c/webdriver/pull/1362 for the conversation that led to this realization.
This change makes the cross domain middleware conditional (defaulting to the current behavior).
This way Appium can pass in 'false' based on a flag, for better server security.
=> make allowing CORS conditional

lib/basedriver/driver.js, package.json
`static` variables are unsupported EcmaScript (just experimental). Usage of `static` variables is experimental and seems to have been broken by a later babel version
=> Do not use static variables yet

lib/jsonwp-proxy/proxy.js
It's a bit confusing to see [JSONWP Proxy] mixed in with W3C sessions, so choose a more neutral name.
=> rename the jsonwp proxy logger so it's less confusing in the logs

lib/express/middleware.js
It looks like Chrome is quite sensitive to such stuff: http://williambert.online/2013/06/allow-cors-with-localhost-in-chrome/
=> Tune the list of allowed headers for CORS

lib/express/middleware.js
webdriverio apparently now sends the `user-agent` header, so for it to work over the web we need to add that to the cors header list.
=> add user-agent to list of cors headers

lib/jsonwp-proxy/protocol-converter.js, test/jsonwp-proxy/protocol-converter-specs.js
Addresses https://github.com/appium/appium/issues/12085
=> Handle setValue API call conversion between protocols

lib/basedriver/driver.js
We should not set timeouts for commands that belong exclusively to the umbrella driver
=> Apply command timeout only if queuing is enabled

lib/basedriver/desired-caps.js
We have two warnings when a boolean capability is passed in. One generic (removed here) and one specific to the actual capability (see https://github.com/appium/appium-base-driver/blob/master/lib/basedriver/commands/session.js#L114-L129).
The current situation leads to unnecessary logging (taken from https://github.com/appium/appium/issues/12186#issue-411719882)
```
[debug] [BaseDriver] Creating session with W3C capabilities: {"alwaysMatch":{"platformNa...
[BaseDriver] Boolean capability passed in as string. Functionality may be compromised.
[BaseDriver] Boolean capability passed in as string. Functionality may be compromised.
[BaseDriver] Boolean capability passed in as string. Functionality may be compromised.
[BaseDriver] Boolean capability passed in as string. Functionality may be …
```
=> Remove generic string->boolean warning

lib/basedriver/commands/find.js, lib/basedriver/device-settings.js, test/basedriver/commands/find-specs.js
closes https://github.com/appium/appium/issues/12209
@jlipps Can you give me a good example app for `if (screenAR === shotAR)` lines I can confirm?
I simply commented out for now. If we do not need this, I would like to remove them.
---
will update https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/image-elements.md later
---
_find by image_ feature returns wrong coordinate in Android and iOS case.
test cases in below test section fails even it compares same image/element.
In [here](https://github.com/appium/appium-base-driver/blob/4eab674f92acfb1dd958fd48c9bbc9399d0d4e74/lib/basedriver/commands/find.js#L344-L359), Appium scales screenshot to window size. Then, Appium uses the scaled image as an input for `compareImages`.
e.g.
The screenshot is `1080x1920`. The window …
=> Fix find element wrong coordinate

lib/basedriver/commands/find.js, lib/basedriver/commands/images.js, lib/basedriver/device-settings.js, lib/basedriver/image-element.js, test/basedriver/commands/find-specs.js
Fix remaining issue in https://github.com/appium/appium-base-driver/pull/306/files#r261480026 .
In the PR, I fixed a template image had different width/height with device screen, but it can be fixed scaling them up/down upto match to device width/height.
But the ratio issue has also below case.
example:
- A user has a template image which is scaled down from `750 x 1314 pixels` image to `187 x 328 pixels` in order to decrease their storage when he store the template image.
- The user uses the scale downed image as the next test case
- Then, the scaled image does not match in current find by image logic since Appium cannot determin what ratio should be scaled the template up/down
- Users must scale them up the image in the user side every time.
To resolve the case, I introduced …
=> Fix template scale in find element by image

lib/basedriver/desired-caps.js, lib/jsonwp-proxy/proxy.js
also add a log line i found helpful
=> add isArray to cap validation strategies

test/basedriver/driver-tests.js
turns out `B.delay(0)` was not enough to allow the current command to actually spin up and assign its cancel promise method. /cc @imurchie
=> fix flakey unexpected shutdown test

lib/basedriver/helpers.js
The `reject` argument is expected to be a valid error object
=> Fix the error which is thrown on download failure

.travis.yml, lib/jsonwp-proxy/protocol-converter.js, test/jsonwp-proxy/protocol-converter-specs.js
After digging into https://github.com/appium/appium/issues/12218 I think the best solution is to proxy W3C `/property/:prop` commands through to JSONWP as `/attribute/:attr`.
So, for example, if a W3C session has this endpoint called
`GET: /session/123/element/456/property/value`
and it's being proxied to a JSONWP server, it should be proxied as
`GET: /session/123/element/456/attribute/value`
=> Make proxy convert /property to /attribute

lib/basedriver/driver.js
Just a little more clarity about unrecognized capabilities, so they are listed much like the real capabilities, instead of buried.
=> Be more explicit about unrecognized caps

lib/protocol/routes.js
`jsonObj.signalStrength` can be `0`. Then, if appium gets only `signalStrength`, the returned value will be `undefined`.
```
0 || undefined //=> undefined
0 || 0 //=> 0
```
Noticed it in https://github.com/appium/python-client/pull/357...
=> fix handling 0 in gsmSignal

lib/jsonwp-proxy/proxy.js
The current implementation guarantees that we will get `[object Object]` in the logs, since if `resBody.value.message` exists, `_.isEmpty(message)` will always be `false`, and `message` will be an object.
=> Only get message from error

lib/jsonwp-proxy/proxy.js
Added an optional parameter to the JWProxy constructor to allow keeping the connection open as long as it is being used.
For example, enabling it for the connection to iOS' WebDriverAgent increases performance.
=> added keepalive option to JWProxy

lib/basedriver/commands/find.js, lib/basedriver/device-settings.js, lib/basedriver/driver.js, lib/basedriver/image-element.js, test/basedriver/image-element-specs.js
closes https://github.com/appium/appium/issues/12506
- Store the result of find by image in `ImageElement`
- It is available only when `getMatchedImageResult` is `true` via settings API
- Users can get the data via `getAttribute` API as `visual`
- e.g. Ruby: `element.visual`, Python: `element.getAttribute('visual')` etc
```ruby
> @driver.update_settings({ fixImageTemplateScale: true, getMatchedImageResult: false })=> nil
> @core.wait { @@driver.find_element_by_image AppiumLibCoreTest.path_of('test/functional/data/test_ios_button.png') }
=> #<Selenium::WebDriver::Element:0x7144c4bf699ffe78 id="appium-image-element-758743a6-7c14-4a90-932c-be7d247faef8">
> image_element.visual
=> nil
> @driver.update_settings({ fixImageTemplateScale: true, getMatchedImageResult: true })=> nil
> image_element …
```
=> add getting result image by find by image

lib/basedriver/commands/session.js, package.json
Create PR for [appium/appium/issues/12766]
Better message for creating session with W3C
=> Better message for creating session with W3C

lib/basedriver/commands/execute-child.js, lib/basedriver/commands/execute.js, lib/basedriver/commands/index.js, lib/basedriver/driver.js, lib/protocol/routes.js, package.json, test/basedriver/driver-e2e-tests.js, test/basedriver/driver-tests.js, test/protocol/routes-specs.js
The [batch command proposal](https://github.com/appium/appium/issues/11021) has been under discussion for some time. To summarize, the original proposal was for a new API that would essentially allow encoding of any Appium command in JSON format, including the use of magic values like `{{<element}}` to refer to an element found in a previous command. This original proposal had several drawbacks:
1. Quite a lot of code would need to be written on both client and server to support the feature. Most of the code would just be encoding/decoding commands from a JSON format.
2. This method interacts poorly with proxying, which is quite common in Appium tests. Say that a batched command set came in involving a context switch, such that subsequent commands in the batch are supposed to target …
=> Add endpoint that receives a webdriver script for batch command execution

lib/jsonwp-proxy/proxy.js, test/jsonwp-proxy/mock-request.js, test/jsonwp-proxy/proxy-e2e-specs.js, test/jsonwp-proxy/proxy-specs.js
Sometimes proxied requests may return really big objects. Calling JSON.parse/stringify on them multiple times is really expensive from both memory and CPU usage perspective.
I've also removed the redirect case for session creation (return code 303), since I didn't find any mentions of this case in specs. Please let me know if this is really needed, so I can put it back.
=> Optimize memory usage by proxy class

lib/jsonwp-proxy/proxy.js
It might be that we proxy /status call first to the downstream driver and it responds in W3C style (since this is a default setting), but then after createSession request is sent the photo is changed to JSONWP based on the provided caps. This change should properly handle such scenario.
=> Update the logic that determines the session protocol

lib/jsonwp-proxy/proxy.js
`proxyCommand` call already returns an object, so there is no need to perform double conversion there. Also, it only makes sense to call stringily if the body object has been modified to save resources.
=> Improve the logic of proxyReqRes method

lib/express/middleware.js, lib/express/server.js
Last fall CORS was turned off by default for the Appium server. This was a good thing, security-wise. However, it meant that async script execution in web contexts would fail unless it was turned on _everywhere_.
=> feat: Allow CORS for receiving async responses

lib/basedriver/helpers.js, test/basedriver/helpers-e2e-specs.js
Hey there,
I figured out HockeyApp responds with `Content-Type: application/zip; charset=utf-8` (which I agree makes no sense). I suggest we relax the Content-Type header test to handle such cases.
=> Handle Content-Type with parameter

lib/protocol/routes.js, test/protocol/routes-specs.js
Will update param in https://github.com/appium/appium/blob/0500ce828789f0bc0e91e39183db7189195c8ec9/commands-yml/commands/element/attributes/replace-value.yml later (and setValueImmediate)
As `sendKeys`, we can accept both value and text as MJSONWP and W3C.
We also can accept them in replaceValue and setValueImmediate like https://github.com/appium/appium-espresso-driver/pull/484
=> feat: accept text for setValueImmediate and replaceValue as W3C

lib/jsonwp-proxy/proxy.js
Previously a warning was always logged if the server was returning 400+ error code. Now we are being smarter about it and only raise a warning if the retrieved response is really broken.
=> fix: Properly log request errors

lib/jsonwp-proxy/proxy.js
W3C protocol requires the session identifier to be returned as one of `value` keys:
https://travis-ci.org/appium/appium-chromedriver/jobs/574990616#L563
=> fix: Fix session identifier retrieval for W3C protocol

lib/jsonwp-proxy/protocol-converter.js, lib/jsonwp-proxy/proxy.js
the idea is to add `status` and `sessionId` fields to getStatus responses if the call was made before session creation request has been sent
Addresses https://github.com/appium/appium/issues/13161
=> fix: Patch downstream responses for unknown upstream protocol

lib/basedriver/helpers.js
Remove the situation where the app is found in the cache, and we get
```
[BaseDriver] Using downloadable app 'http://appium.s3.amazonaws.com/TestApp10.2.app.zip'
[debug] [BaseDriver] Last-Modified: Thu, 27 Apr 2017 23:29:04 GMT
[debug] [BaseDriver] Reusing already downloaded application at '/var/folders/pq/46v__b_n7tq3ftb5ccnjt6rw0000gn/T/201984-86549-1foenne.m7ix/TestApp.app'
[BaseDriver] Reusing the previously downloaded application at '/var/folders/pq/46v__b_n7tq3ftb5ccnjt6rw0000gn/T/201984-86549-1foenne.m7ix/TestApp.app'
```
=> fix: remove redundant log line on cached app found

test/basedriver/driver-e2e-tests.js
Node `12.11.0` throws syntax errors slightly differently:
```
$ node
Welcome to Node.js v12.10.0.
Type ".help" for more information.
> }
Thrown:
}
^
SyntaxError: Unexpected token }
>
```
```
$ node
Welcome to Node.js v12.11.0.
Type ".help" for more information.
> }
Thrown:
}
^
SyntaxError: Unexpected token '}'
>
```
=> fix: fix the build for Node 12.11.0

docs/mjsonwp/errors.md, lib/protocol/errors.js, test/protocol/errors-specs.js, test/protocol/protocol-e2e-specs.js
Selenium client is complaining about the error codes we return from these exceptions. See, for example, https://discuss.appium.io/t/exception-in-thread-main-org-openqa-selenium-unsupportedcommandexception-method-has-not-yet-been-implemented/27958
=> fix: Adjust the error codes for NotImplementedError

lib/express/server.js
We were observing Python client throwing random disconnect errors when keepAlive mode on the client side is enabled. This could be happening because the server closes the connection before the client times out. So we need to make sure the default server timeout is greater than the client one and 10 minutes should be enough. See https://shuheikagawa.com/blog/2019/04/25/keep-alive-timeout/ for more details
=> fix: Explicitly set keep-alive server timeout

lib/jsonwp-proxy/proxy.js
The documentation states that setting `forever` is equal to setting the `agent` to `http(s).Agent({keepAlive:true})`. This means we should not set `agent` to `false` if `forever` is `true`
=> fix: Fix the request options for different keepAlive values

lib/basedriver/commands/event.js, test/basedriver/commands/event-specs.js
Filter events with `type`.
Is this expected way? @jlipps 
The  usage in Ruby is:
```ruby
@driver.logs.events
#=> {"commands"=>[{"cmd"=>"timeouts", "startTime"=>1573544038106,
@driver.logs.events 'wdaStartAttempted'
#=> {"wdaStartAttempted"=>[1573546058909, 1573546084570]}
@driver.logs.events ['wdaStartAttempted']
#=> {"wdaStartAttempted"=>[1573546058909, 1573546084570]}
@driver.logs.events ['wdaStartAttempted', 'wdaStarted']
#=> {"wdaStartAttempted"=>[1573546058909, 1573546084570], "wdaStarted"=>[1573546096204]}
```
---
https://github.com/appium/appium-base-driver/pull/365
=> feat: add filtering log events with type (related to #365)

lib/basedriver/README.md, lib/basedriver/commands/session.js, lib/basedriver/driver.js, test/basedriver/driver-e2e-tests.js, test/basedriver/driver-tests.js
According to https://github.com/appium/appium/issues/13631 we still have memory leaks due to weird promise cancelation logic. IMHO promise cancelation itself is evil in its current implementation and I would rather avoid using it. 
BREAKING CHANGE: The current refactoring is breaking and changes `onUnexpectedShutdown` to a normal event, which is emitted by the driver when it is shut down unexpectedly. I've also checked the depending drivers and it looks like only the umbrella driver uses this promise, so we'll have to change that implementation after the major version bump
=> refactor: Prefer event emitting to promises cancelation

lib/basedriver/driver.js
Should address https://github.com/appium/appium/issues/13631#issuecomment-558505896
=> fix: make sure the listener gets removed after the command executor is completed

lib/basedriver/helpers.js, test/basedriver/helpers-specs.js, test/jsonwp-proxy/protocol-converter-specs.js, test/jsonwp-proxy/proxy-specs.js, test/jsonwp-proxy/url-specs.js, test/jsonwp-status/status-specs.js
If `parseCapsArray` is passed an array, it ought to just pass it back as is.
=> fix: when parsing cap array, pass array through

lib/basedriver/device-settings.js
I think such warning messages only make more confusion rather than helping to resolve the problem. I'd rather let the server to decide which setting names are correct and which aren't.
See https://github.com/appium/appium/issues/13681#issuecomment-562089828 for more details.
=> refactor: Change the setting update validation, so we don't print unnecessary warnings

lib/basedriver/helpers.js
Previously we were deleting apps when their count reaches some particular amount. This is not the best approach for parallel driver sessions, so I changed the approach to only delete the cached apps when they are not being used for 24 hours (or on server process termination). It will also be necessary to update the driver and prevent cached apps modification from outside of the base driver module
=> refactor: Change the applications caching logic

lib/basedriver/helpers.js, package.json
Asynchronous calls in onExit handler are not supported., since the event loop does not exist anymore. See https://nodejs.org/api/process.html#process_event_exit
=> fix: Perform synchronous removal of applications cache

lib/basedriver/helpers.js
The `dispose` handler is called each time an entry is removed from LRU cache, which might create some excessive logging on process exit. The PR changes the logic to only print the log when necessary to not confuse users.
=> chore: Tune logging for applications cache items disposal

lib/protocol/protocol.js
In the case of ending sessions, and when a request is for a session that does not exist, the connection should not remain alive.
=> fix: terminate socket on DELETE session and NoSuchDriverError

package.json
Another macOS notarization warning.
`BadZippedApp.zip` in test fixture has `Couldn't read PKZip signature` warning message. We can remove `test` stuff from the package, simply.
=> fix: remove test/ build/test for notarization to fix a warning message

lib/basedriver/commands/find.js, lib/basedriver/image-element.js, package.json, test/basedriver/commands/find-specs.js, test/basedriver/image-element-specs.js
https://github.com/appium/appium/issues/13883
Depends on https://github.com/appium/appium-support/pull/169
After this change, we can get `score` image attribute like below:
- client (Ruby)
```ruby
image_element =  @@driver.find_element_by_image AppiumLibCoreTest.path_of('test/functional/data/test_ios_button.png')
=> #<Selenium::WebDriver::Element:0x4de9c1e10ffa87de id="appium-image-element-e3b9dd5b-0c26-47a7-838a-6d72d61f62e7">
> image_element.score
=> 0.9313163161277771
```
- server
```
[HTTP] --> GET /wd/hub/session/97e811cd-d675-4f2c-a00e-ec79f5b1631b/element/appium-image-element-e3b9dd5b-0c26-47a7-838a-6d72d61f62e7/attribute/score
[HTTP] {}
[debug] [W3C (97e811cd)] Calling AppiumDriver.getAttribute() with args: ["score","appium-image-element-e3b9dd5b-0c26-47a7-838a-6d72d61f62e7","97e81 …
```
=> feat: add score attribute for image element

lib/basedriver/helpers.js
Currently caching is only considered based on the Last-Modified header values. Although it also makes sense to consider Cache-Control values there
=> feat: Consider the content of Cache-Control header for application caching

lib/express/idempotency.js, lib/express/middleware.js, lib/express/server.js, package.json, test/basedriver/driver-e2e-tests.js, test/express/server-specs.js
The idea behind that is to be able to properly handle client side retries. 
How this is supposed to work:
- The client adds a randomly generated `X-Idempotency-Key` header to each request we'd like to make idempotent (each request must have a different value). The server itself only considers header presence in POST and PUT requests.
- The server temporarily stores the response stream of the marked request in the internal LRU cache. After the request is done then its result is serialised to the file system.
- If the second request with an idempotency key is coming and no matches are found then the request proceeds further
- If there is an active request with the same key then the response stream of that request will be rerouted to the current one, so the client would receive the same …
=> feat: Add requests idempotency verification on the server side

lib/express/static.js, static/test/guinea-pig-app-banner.html, static/test/guinea-pig-scrollable.html, static/test/guinea-pig.html
This has bugged me for a while. Our guinea pig pages put the date as a number. Move to a human-readable date.
=> fix: put full date on the static guinea pig pages

lib/protocol/routes.js, test/protocol/routes-specs.js
Chrome browser support `/session/:sessionId/goog/cdp/execute` endpoint.
Selenium bindings, afaik Java, Python and Ruby, have the endpoint.
We also can support it for chromebrowser. Below is an example.
```
> @driver.execute_cdp 'Page.getResourceTree'
=> {"frameTree"=>
{"frame"=>{"id"=>"39B491DE0055515F0F352E11054854F9", "loaderId"=>"3E11DD1F2E9E020331C94E2E02E608E7", "mimeType"=>"text/plain", "securityOrigin"=>"://", "url"=>"data:,"},
"resources"=>[{"contentSize"=>0, "mimeType"=>"text/plain", "type"=>"Document", "url"=>"data:,"}]}}
```
https://chromedevtools.github.io/devtools-protocol
Without this change, Appium returns below error.
```
[HTTP] --> POST /wd/hub/session/ba1e624d-d767-4059-a499-18e1aa330651/goog/cdp/execute
[HTTP] {"cmd":"Page.getResourceTree","params":{}}
[debug] [HTTP] No …
```
=> feat: add calling chrome devtools endpoint for chromium

.gitignore, lib/express/server.js, lib/jsonwp-proxy/proxy.js, package.json, test/jsonwp-proxy/mock-request.js, test/protocol/protocol-e2e-specs.js
BREAKING CHANGE:
- The request method of Proxy class now accepts and returns axios-specific values
- The default value of keepAlive setting has been changed to `true`
=> refactor: Use axios for the actual proxy implementation instead of the deprecated request module

lib/jsonwp-proxy/proxy.js
It does not make much sense to have full stack traces for system errors in logs, which look redundant:
```
WARN [07-03-30:969] WD Proxy connect ECONNREFUSED 127.0.0.1:8100
352dbug [07-03-30:979] WD Proxy Error: connect ECONNREFUSED 127.0.0.1:8100
353dbug [07-03-30:979] WD Proxy     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
```
=> chore: do not print full stack traces for connection errors

static/test/welcome.html
In simulator safari ios I get incorrect viewport width and height. Moreover it does not changed after rotation. It fixed only if viewport meta tag is set.
=> fix(welcome page): add "viewport" meta tag

lib/jsonwp-proxy/proxy.js
It does not make much sense to show a full stack trace there, since it does not contain any useful info. See https://dev.azure.com/AppiumCI/7a2a2919-d2b4-4720-a6c3-3a639f9bb2e0/_apis/build/builds/9842/logs/35 for more details
=> chore: Print a compact message for 'socket hang up' error

lib/jsonwp-proxy/proxy.js
Related to https://github.com/appium/appium/issues/14416
Previously we were creating a separate connections pool for each request, which is bad. The connections pool must be shared in scope of a single JWProxy instance
=> fix: Properly assign connection pools for JW proxy

lib/jsonwp-proxy/proxy.js
There requests are always made on localhost level, so there's no need to route them to a proxy server
=> chore: Never apply automatic proxy config to JWProxy requests

lib/express/server.js, test/express/server-e2e-specs.js
This change ensures there will be no unexpected delays when appium process receives SIGINT or SIGTERM
=> chore: Always destroy active sockets on server shutdown

lib/basedriver/capabilities.js, test/basedriver/capabilities-specs.js
Currently, if we provide W3C capabilities and prefix standard W3C capabilities (platformName, browserName, etc...) it rejects the session. This PR is made, in the spirit of forgiveness, to allow standard capabilities to be prefixed with `appium:` and let the offenders off with a `log.warn`.
Example of session creation caps that will fail in Appium's current state
```
{
"capabilities": {
"firstMatch": [{}],
"alwaysMatch": {
"appium:platformName": "iOS",
"appium:browserName": "safari",
"appium:automationName": "XCUITest",
"appium:deviceName": "iPhone Simulator",
"appium:platformVersion": "13.4",
"sauce:options": {
"appiumVersion": "1.16.0"
}
}
}
}
```
=> fix: allow prefixed standard capabilities

lib/express/middleware.js, lib/express/server.js, test/express/server-e2e-specs.js, test/express/server-specs.js, test/protocol/protocol-e2e-specs.js
All clients expect responses to be returned as valid json objects and throw exceptions in case of plain text: https://gist.github.com/TransmitTomerDavid/31132cd2ea3ce3c4514e24494ad8f504
=> fix: Return proper responses to unexpected errors

lib/express/server.js, test/express/server-specs.js
somewhere along the way plugins were broken. Maybe a change in Express? Anyway, need to put the catchall handler at the very end, after any plugin might be registered.
=> fix: catchall handler should be added after plugin application

lib/protocol/protocol.js
Addresses https://github.com/appium/appium/issues/14894
=> fix: Never destroy sockets explicitly

lib/express/server.js
Someone reported a bug where they tried to background the app for 30 minutes and it didn't work. Now we know why!
=> fix: 10 minute connection timeout is too low for some use cases

lib/basedriver/commands/find.js, lib/basedriver/commands/images.js, package.json, test/basedriver/commands/find-specs.js
Hi,
For my appium use case, there may be multiple places on the screen which has the same image and I'd like to find them all.
I am not a javascript dev by trade, so would definitely welcome any comments on this!
Thanks
Alex
Depends on these changes in appium-support: https://github.com/appium/appium-support/pull/212 -> now published in 2.50
~TODO: bump the appium-support version number to bring in those changes~
=> feat: Support multiple image match in findByImage

lib/jsonwp-proxy/proxy.js
Fix https://github.com/appium/appium/issues/15132
This was when we modify keepalive stuff in https://github.com/appium/appium-base-driver/pull/416/files .
Should the timeout respect the constructor's one?
=> fix: timeout of JWProxy for httpAgent and httpsAgent

lib/basedriver/driver.js, lib/basedriver/helpers.js
Related to https://github.com/appium/appium-android-driver/pull/684
These helpers are only used in android driver and nowhere else. Also, logically, it does not make any sense to have this code in the base driver, since it is not cross-platform and is only specific to android driver
=> refactor: Remove swipe-related helpers from the base driver

lib/basedriver/commands/images.js
Calling `toString('base64')` should only when the visualization is not string and has value.
https://github.com/appium/appium-plugins/runs/2636842428?check_suite_focus=true
=> fix: convert element.visualization to string

lib/protocol/routes.js, test/protocol/routes-specs.js
Related to https://github.com/appium/appium-xcuitest-driver/pull/1315
2.0 base driver already has this. This PR is for the next 1.x release.
=> feat: add releaseActions as w3c actions (from 2.0 branch)

lib/basedriver/helpers.js, test/basedriver/helpers-specs.js
In my testing, I've found that `/usr/bin/unzip` is a 3x speedup over a native-JS implementation (which we currently use).  This can be significant in large files.
To maintain cross-platform compatibility, the `unzipApp()` helper function will fall back to the native JS implementation where `/usr/bin/unzip` is not available (Windows).  It will also retry using the native implementation if `/usr/bin/unzip` fails for any other reason.  Given `.zip` files are _validated_ prior to this call, it's unlikely that would occur unless there is something wrong with system unzip itself.
I've added a couple trivial tests here, but to test it "properly" would require a fair bit of refactoring.
TODO: Port to `@appium/base-driver` and configure CI to run E2E tests on win32.
=> feat(helpers): leverage system unzip where available

package.json
this version has https://github.com/appium/appium-support/commit/873351aacc0402bcb229bad928abd1ad2f9c4a4b
=> chore: bump min appium-support version

lib/basedriver/helpers.js
Glob can filter items while searching. There is no need to do it again after all items are returned
=> chore: Optimize bundle lookup in the extracted archive

lib/protocol/routes.js, test/protocol/routes-specs.js
(Will create the same PR to appium/2.0 later)
I noticed selenium 4 clients sent `/se/log` paths since these routes were not in W3C spec.
https://github.com/appium/python-client/issues/630
Some clients like Ruby lib already support the old format in W3C, but it would be better to support `/se/log` paths for possible selenium compatible clients.
https://github.com/appium/ruby_lib_core/blob/1632637fd872c0b80dfb97b8514ada6a7164eebf/lib/appium_lib_core/common/command/w3c.rb#L50
Python client 2 (selenium 4 bases) is still beta, so we can say it works over Appium 1.22.0 after this (and publish a new rc)
=> feat: add /se for selenium 4

package.json
Hi Team,
We did a minor change in Asyncbox Library 2.9.1 version specific to waitForCondition method which is been used in implicit wait function. 
Kindly review and accept the PR
Thanks
Jayandran Sampath
=> fix: Jay/Sriram -Update Asyncbox version

lib/basedriver/helpers.js, test/basedriver/helpers-specs.js
After longer meditation on LRU cache sources it turns out that `has` check does not actually care about expired items removal. Only the `get` check does that.
Also, it could be that the internal structure of the cached file/folder is changed while it's being cached. For now I've added a very simple (and fast) integrity check for cached folders, which makes sure that the amount of items in the folder (files and subfolders) has not been decreased since the last check.
Related to https://github.com/appium/appium/issues/16109
=> fix: Update apps cache behaviour for expired items
