appium/appium-base-driver

lib/command.js, lib/commands/index.js, lib/commands/session.js, lib/driver.js
This seems better, no more `this` magic, better separation of concerns.
Also splitting the commands into logical categories.
=> Commands as arrow functions passing driver

lib/commands/session.js, lib/desired-caps.js, lib/driver.js, package.json, test/capability-specs.js, test/driver-e2e-specs.js, test/driver-e2e-tests.js, test/driver-specs.js, test/driver-tests.js
depends upon https://github.com/appium/node-mobile-json-wire-protocol/pull/9
=> add desired cap validation

index.js, lib/commands/index.js, lib/commands/settings.js, lib/device-settings.js, package.json, test/driver-e2e-tests.js
- @jlipps @Jonahss please review
=> Adding new device-settings

lib/driver.js
@jlipps @Jonahss please review
=> Adding this.settings and setting it to null

lib/commands/find.js, lib/commands/timeout.js, package.json
implicitWaitForCondition + added locator check.
=> Common find related stuff

lib/commands/session.js, lib/commands/timeout.js, lib/device-settings.js, lib/driver.js
I think it is enough for iOS, so much simpler. ping @jlipps @moizjv 
Android has extra logic (or use different) on top of that, I'll let Moiz figure it out.
=> Adds reset + command timeout improvements

lib/helpers.js
Had already fixed it, it is the same as the current solution, but more idiomatic. 
ping @jlipps @Jonahss
=> simpler download logic

lib/commands/session.js, lib/driver.js, lib/helpers.js
ping @jlipps @moizjv @Jonahss @imurchie @scottdixon , gettng rid of `app === ''` case, it's better to get a Null/Undefined exception and fix it.
=> Option initialization fix + Avoids empty string app cap.

lib/commands/timeout.js, lib/driver.js
ping @jlipps 
It's more flexible this way, and there cannot be 2 timeouts running at the same time.
=> Better command timeouts

lib/driver.js, test/driver-tests.js
By default a driver does not proxy anything.
=> Add proxy helper methods

lib/driver.js, test/driver-e2e-tests.js
=> Remove error handling from proxy methods

lib/driver.js, lib/helpers.js, package.json
Couldn't update Bluebird, it will require more than a couple minutes. Might have to be updated appium-wide.
Anyways, created a ticket for bluebird, but updated lodash and others. Thank goodness for tests.
=> update dependencies, most notably: lodash to v4

lib/commands/timeout.js, test/driver-tests.js
Begin working on https://github.com/appium/appium/issues/6400
=> Add timeouts methods

lib/basedriver/commands/find.js
The exact specification of what to return in a findElement command was a little hard to find. This was the first place I looked, so a good place to put the answer.
@imurchie for review :)
=> Add comment for find command return type

lib/mjsonwp/validators.js, test/mjsonwp/validator-specs.js
=> Allow data: scheme for protractor tests

lib/basedriver/desired-caps.js
Goes with this PR: https://github.com/appium/appium/pull/6215
=> Added YouiEngine to the list of automationName

test/mjsonwp/fake-driver.js, test/mjsonwp/mjsonwp-specs.js
=> Add test for driver not throwing error

lib/mjsonwp/routes.js, test/mjsonwp/routes-specs.js
@jlipps @imurchie 
I know this involves changing the hash for the gulp tests. But before thats done want to make sure this pull is ok. 
Here is the spec for this [route](https://github.com/SeleniumHQ/mobile-spec/blob/master/spec-draft.md#device-orientation)
=> added rotation routes

lib/basedriver/desired-caps.js, lib/jsonwp-proxy/proxy.js, lib/mjsonwp/errors.js, lib/mjsonwp/mjsonwp.js, test/mjsonwp/errors-specs.js, test/mjsonwp/mjsonwp-specs.js
- ProxyRequestUnsuccessfulError will be thrown for all unsuccessful proxy requests, ProxyRequestUnsuccessfulError will contain the actual error route cause information in [`jsonwp`](https://github.com/sravanmedarapu/appium-base-driver/blob/5a66d7d9ec4772a9b88f9ba6545821b098f6c82f/lib/mjsonwp/errors.js#L316)
=> Implemented throwing ProxyRequestError

lib/mjsonwp/routes.js, test/mjsonwp/routes-specs.js
@jlipps @imurchie @rafael-chavez 
Adding a new routes to match wda: 
https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/DriverCommand.java#L83
WDA:
https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/Commands/FBElementCommands.m#L46
new spec:
https://w3c.github.io/webdriver/webdriver-spec.html#get-element-rect
=> adding rect routes

lib/jsonwp-proxy/proxy.js
On slow systems the proxy can timeout. Increase.
=> Give a long timeout on proxy

lib/basedriver/helpers.js
@imurchie : Look at this whenever you get time. we want to add support to copy app from windows network share. I know this is not perfect implementation. So, if you could help with right approach, it will be awesome. Also, I would like to add unit test but I am not sure how that could run with CI.
=> Copy from WindowsNetworkShare

.travis.yml, lib/jsonwp-proxy/proxy.js
The length we have right now is almost useless.
=> Extend the length of the proxy req/res we log

docs/mjsonwp/protocol-methods.md, lib/mjsonwp/routes.js, test/mjsonwp/routes-specs.js
this apis is to read the capability data of device
=> add apis to read capability data

README.md, index.js, lib/basedriver/driver.js, lib/basedriver/logger.js, lib/express/logger.js, lib/jsonwp-proxy/proxy.js, lib/logger/README.md, lib/logger/logger.js, lib/mjsonwp/mjsonwp.js, package.json, test/logger/helpers.js, test/logger/logger-force-specs.js, test/logger/logger-normal-specs.js, test/logger/logger-test-specs.js
Another step toward unification.
=> Move appium-logger into base driver

lib/jsonwp-proxy/proxy.js
There are use cases for having the connection open longer. See https://github.com/appium/appium/issues/7643
=> Add configurable request timeout to proxy

lib/basedriver/commands/session.js, test/basedriver/driver-tests.js
some people have been doing this and it doesn't make sense
=> error out if someone tries to use both fullReset and noReset together

index.js, lib/mjsonwp/index.js, lib/mjsonwp/routes.js, test/mjsonwp/routes-specs.js
=> Add METHOD_MAP to public exports, so it can be used by other modules

lib/jsonwp-proxy/proxy.js
This is needed to simplify xcuitest-driver logic and get rid of unnecessary flags
=> Add proxy method to verify whether it has a request in progress

lib/basedriver/commands/session.js, lib/basedriver/desired-caps.js, lib/basedriver/driver.js, test/basedriver/driver-e2e-tests.js, test/basedriver/driver-tests.js
taking a stab at https://github.com/appium/appium/issues/7768
review please @imurchie @dpgraham!
=> add event timing framework to base driver

docs/mjsonwp/protocol-methods.md, lib/mjsonwp/routes.js, test/mjsonwp/routes-specs.js
Use snake case instead of camel.
=> Fix casing on record screen endpoints

lib/basedriver/helpers.js, package.json, test/basedriver/helpers-specs.js
* Added a test for unzipFile (which uses adm-zip)
* Tested that it worked with adm-zip and then failed once adm-zip was taken out
* Replaced 'adm-zip' with zip.extractAllTo from appium-supprt
(reviewers @jlipps @imurchie)
=> Removed adm-zip

lib/mjsonwp/mjsonwp.js, lib/mjsonwp/routes.js, test/mjsonwp/fake-driver.js, test/mjsonwp/mjsonwp-specs.js, test/mjsonwp/routes-specs.js
this introduces a 'makeArgs' option for the spec which allows handling of more complex scenarios.
@mykola-mokhnach this should do the trick.
=> allow both 'value' and 'text' params for setValue

lib/basedriver/device-settings.js, package-lock.json
simple fix for https://github.com/appium/appium/issues/3585
=> warn when a setting does not exist

lib/mjsonwp/routes.js, test/mjsonwp/routes-specs.js
Adding endpoints for the new methods we're adding on android emulators.
=> Add new endpoints

lib/mjsonwp/routes.js, test/mjsonwp/routes-specs.js
This PR depends on https://github.com/appium/appium-ios-simulator/pull/126
=> Add 'enabled' parameter to toggle_touch_id_enrollment endpoint

lib/express/server.js, lib/express/static.js, package.json, static/test/guinea-pig-app-banner.html, test/express/server-specs.js
So we can test what happens when a page has the app download banner at the top.
=> Add static page with app banner

lib/basedriver/commands/timeout.js, lib/mjsonwp/routes.js, test/basedriver/driver-tests.js, test/mjsonwp/routes-specs.js
* Some of the routes just point to the an existing command
* Implemented the 'timeouts' endpoint
* The rest of them are just new routes with different command names that are to be implemented by drivers (most of them are web commands)
=> w3c routes

.gitignore, .npmrc
=> Stop making package-lock.json file

lib/basedriver/helpers.js, test/basedriver/helpers-e2e-specs.js
Addresses https://github.com/appium/appium/issues/10003
=> Assume a file is located on SMB server if the path starts with double backslash

lib/mjsonwp/errors.js, lib/mjsonwp/mjsonwp.js, test/jsonwp-proxy/proxy-specs.js
* Changed the logger to be 'W3C' when it's W3C protocol and 'MJSONWP' when it's MJSONWP protocol
* Also fixed an outdated test
(Note: I'll have at least 1 or 2 more PR's like this that rename MJSONWP to Protocol, I wanted to do it one-at-a-time to keep each PR simple)
=> Renamed MJSONWPError to ProtocolError

lib/basedriver/helpers.js, test/basedriver/helpers-e2e-specs.js
Addresses https://github.com/appium/appium/issues/7203
=> Print more advanced error message for non-supported protocols

lib/protocol/errors.js, test/protocol/errors-specs.js
This should fix https://github.com/appium/appium/issues/10286, since selenium clients such as java one decide which exception should be thrown based on the standard codes/descriptions.
=> Add missing error codes

lib/protocol/routes.js, test/protocol/routes-specs.js
I would like to generalize iOS and Android clipboards interaction primitives and create high-level wrappers over them
=> Add endpoints for system clipboard interaction

lib/express/websocket.js, test/basedriver/websockets-e2e-specs.js
This will allow the server to resolve ip addresses of remote clients
=> Send request along with websocket instance

index.js
This is needed by https://github.com/appium/appium-xcuitest-driver/pull/652
=> Publish the path to static resources root

lib/basedriver/commands/images.js, lib/basedriver/commands/index.js, lib/protocol/routes.js, package.json, test/basedriver/commands/images-specs.js, test/protocol/routes-specs.js
Based on https://github.com/appium/appium-support/pull/65
=> Add an universal endpoint for images comparison

lib/basedriver/commands/settings.js
I have created a small helper tool for finding missing await calls. It is pretty dumb yet, but managed to find some issues so far.
=> Add missing await

lib/protocol/routes.js, test/protocol/routes-specs.js
This will allow to emulate sending of complex key sequences. See https://github.com/appium/appium-uiautomator2-server/pull/157 for more details
=> Add an optional flags parameter to press_key_code endpoint

lib/jsonwp-proxy/proxy.js, lib/protocol/protocol.js
Make sure proxied errors get through to the error handling code.
Toward fixing https://github.com/appium/appium/issues/10703
=> Check for proxied error

lib/jsonwp-proxy/proxy.js, lib/protocol/errors.js, lib/protocol/protocol.js
The second PR to resolve https://github.com/appium/appium/issues/10809#issuecomment-395636141
=> Avoid throwing proxy request error inside command call

lib/protocol/routes.js, test/protocol/routes-specs.js
for https://github.com/appium/appium-android-driver/pull/378
I've tested with
- https://github.com/appium/ruby_lib_core/pull/94
- https://github.com/appium/appium-android-driver/pull/378
=> add format in deviveTime as a parameter

lib/basedriver/desired-caps.js
Add Tizen tag in desired-caps.js for supporting Tizen
=> Add Tizen tag in desired-caps.js for supporting Tizen (#1)

lib/jsonwp-proxy/proxy.js, test/jsonwp-proxy/proxy-specs.js
This should resolve https://github.com/appium/java-client/issues/976
=> Properly handle MJSONWP responses with non-zero status and return code < 400

lib/protocol/routes.js, test/protocol/routes-specs.js
Addresses https://github.com/appium/appium/issues/10319
=> Add an optional parameter to /window call

lib/basedriver/commands/timeout.js, lib/jsonwp-proxy/proxy.js, test/basedriver/driver-tests.js, test/basedriver/timeout-specs.js, test/jsonwp-proxy/proxy-specs.js
Addresses the issue from https://api.travis-ci.org/v3/job/415969181/log.txt caused by https://github.com/appium/appium-base-driver/pull/248
=> Apply additional fixes to timeouts handler

lib/jsonwp-proxy/proxy.js, lib/protocol/routes.js, test/protocol/routes-specs.js
Addresses https://github.com/appium/appium/issues/11219
=> Add JSONWP<>W3C mapping for window/handles endpoint

lib/protocol/routes.js, test/protocol/routes-specs.js
Addresses https://github.com/appium/appium/issues/11323
=> Fix setting alert text for W3C protocol

lib/protocol/protocol.js
Addresses https://gist.github.com/jlegorburuJC/ca0ee8b2f724c224f4da1bc590bae5f1#file-appium-log-L183
=> isError lodash verification seems to be not very reliable for us

lib/basedriver/capabilities.js, lib/basedriver/commands/session.js, lib/protocol/errors.js, lib/protocol/protocol.js, test/protocol/fake-driver.js, test/protocol/protocol-e2e-specs.js
I hope this will address https://github.com/appium/appium/issues/11300
=> Fix protocol detection inside the routing function

lib/protocol/protocol.js, test/protocol/protocol-specs.js
This should fix https://travis-ci.org/appium/appium/builds/426921776
=> Fix the way current protocol is determined from execute response

lib/protocol/protocol.js
This should simplify debugging of parallel drivers
=> Append the current session identifier to the protocol name prefix

lib/jsonwp-proxy/proxy.js, test/protocol/helpers.js, test/protocol/protocol-e2e-specs.js
This is supposed to address https://github.com/appium/appium/issues/11380
Please do not merge until the fix is confirmed
=> Limit the count of request agents in the proxy pool

lib/basedriver/commands/session.js, lib/basedriver/desired-caps.js
Addresses https://github.com/appium/appium/issues/10930
=> Allow numbers-as-strings while performing capabilities verification

lib/jsonwp-proxy/protocol-converter.js
Addresses https://github.com/appium/appium/issues/11458
=> Fix protocol conversion for getWindowHandle command

test/express/server-e2e-specs.js, test/express/server-specs.js
I would assume the functional suite is the best place for these tests since they interact with the network.
=> Move server tests to functional set of tests

lib/basedriver/helpers.js, package.json, test/basedriver/helpers-e2e-specs.js, test/basedriver/helpers-specs.js
This change is required by https://github.com/appium/appium-adb/pull/367#discussion_r226311748
I've also refactored a lot of the existing stuff.
=> Make it possible to pass multiple supported extensions to configureApp helper

lib/basedriver/helpers.js, package.json, test/basedriver/helpers-e2e-specs.js, test/express/server-e2e-specs.js
This should resolve race conditions while caching applications download/extractions for parallel sessions
=> Properly synchronize applications caching

lib/basedriver/helpers.js
It will help to avoid issues like https://gist.github.com/daviesdoclc/b28b1308dcb7222225a49c45885c9f0c#file-appium-android-log-L199
=> Automatically fix relative application paths

lib/basedriver/helpers.js
Addresses https://github.com/appium/appium/issues/11754
=> Consider getting file extension from the url if response headers are not useful

lib/basedriver/helpers.js
Addresses https://github.com/appium/appium/issues/11782
=> Make sure the app is not cleaned up if relative path is provided

lib/jsonwp-proxy/protocol-converter.js
Addresses https://github.com/appium/appium/issues/12161
=> Fix /actions body while doing protocol translation

lib/basedriver/helpers.js
Addresses https://github.com/appium/appium/issues/12173
=> Fix application type handling for urls with parameters

lib/basedriver/commands/find.js, lib/basedriver/driver.js
so other drivers/plugins can use it nicely.
=> factor out image element registration

lib/jsonwp-proxy/protocol-converter.js
Resolves https://github.com/appium/appium/issues/12927
=> Add a workaround to POST /window W3C call

lib/jsonwp-proxy/protocol-converter.js
Addresses https://github.com/appium/appium/issues/12989
=> Add protocol conversion for setFrame call

lib/jsonwp-proxy/proxy.js, lib/protocol/helpers.js, lib/protocol/protocol.js, lib/protocol/sessions-cache.js
Related to https://github.com/appium/appium-base-driver/pull/343
Also did several refactorings
=> Update response handling for proxyReqRes call

index.js, lib/basedriver/capabilities.js
This method is needed to implement https://github.com/appium/appium/issues/13014
=> chore: Export isStandardCap method

lib/jsonwp-proxy/proxy.js
Otherwise the base driver might be too talkative
=> fix: Do not print stack for request errors

lib/jsonwp-proxy/protocol-converter.js, lib/jsonwp-proxy/proxy.js, lib/protocol/helpers.js, lib/protocol/protocol.js
Addresses https://github.com/appium/appium/issues/13161
=> fix: Tune status presence verification for generic protocol

lib/protocol/errors.js
instanceof verification does not always work as expected, so it's better to use duck typing instead
=> fix: Avoid using instanceof verification

lib/basedriver/commands/session.js, lib/basedriver/commands/timeout.js, lib/basedriver/driver.js, test/basedriver/driver-tests.js
Fixes the ugly memory leak related to promises cancelation logic. More details at https://github.com/appium/appium/issues/13321
=> refactor: Replace custom commands queue implementation with async lock

lib/basedriver/desired-caps.js, test/basedriver/capabilities-specs.js, test/basedriver/capability-specs.js
deviceName cap should not be required for all drivers. See https://github.com/appium/appium/issues/13457
=> fix: Make device name non required

lib/basedriver/commands/event.js, lib/basedriver/commands/index.js, lib/protocol/routes.js, test/basedriver/commands/event-specs.js, test/protocol/routes-specs.js
So people can use the event parser timeline in context of their own events!
=> feat: add new route to allow logging of custom events

lib/basedriver/commands/event.js, lib/protocol/routes.js, test/basedriver/commands/event-specs.js, test/protocol/routes-specs.js
in response to https://github.com/appium/java-client/pull/1262#discussion_r342398309
=> feat: add ability to retrieve log events as a new api route

lib/protocol/routes.js, test/protocol/routes-specs.js
https://github.com/appium/appium/issues/13616
=> fix: Sync parameters validation for the old and the new set alert text endpoints

lib/basedriver/helpers.js, package.json
https://github.com/appium/appium-base-driver/pull/375#discussion_r358279078
=> chore: Import rimrafSync from appium-support

lib/basedriver/capabilities.js
It was difficult to discern the capabilities that ought to be changed.
=> refactor: just a little more visibility into unprefixed caps

static/test/shadow-dom.html
Add a simple static html page with shadow content, for testing Appium's ability to automate.
=> feat: add a simple static page with shadow elements

lib/basedriver/commands/find.js
https://github.com/appium/appium/issues/14060
=> chore: Add width/height verification to avoid OOM on image resize

lib/basedriver/image-element.js
Fix for winappdriver click action payload (see https://github.com/appium/appium-windows-driver/pull/69#issuecomment-600772369)
=> fix: Add button to actions payload

lib/express/idempotency.js
Addresses https://dev.azure.com/srinivasansekar/java-client/_build/results?buildId=425&view=logs&j=dcf5f1f5-2eb6-5586-dc7f-e40285fb9e33&t=001cc609-8f94-5735-fd9e-04c1a9cbbffb
=> fix: Avoid ERR_STREAM_WRITE_AFTER_END error

lib/protocol/routes.js, test/protocol/protocol-e2e-specs.js, test/protocol/routes-specs.js
I have added support for POST commands for DoubleClick, ButtonUp and ButtonDown.
=> chore: Define options for for doubleClick, buttonUp\Down routes

lib/jsonwp-proxy/proxy.js, lib/protocol/protocol.js, test/jsonwp-proxy/proxy-specs.js
Something has been broken during migration and it's time to fix it for good.
Affected PR: https://github.com/appium/appium-espresso-driver/pull/576
=> fix: Adjust the validation of proxied requests

lib/basedriver/commands/log.js
This is needed for https://github.com/appium/appium-android-driver/pull/646
=> fix: Make sure getLogTypes returns a promise

lib/basedriver/helpers.js, package.json
Addresses https://github.com/appium/appium/issues/14100
=> fix: Enforce UTF-8 encoding on extracted file names for .ipa archives

lib/express/server.js, lib/protocol/protocol.js, test/express/server-e2e-specs.js, test/express/server-specs.js
These changes are needed in order to support the new plugin architecture for Appium 2.0. I do not believe they are breaking changes since they just add optional arguments, and change the shape of a method which I don't think is used outside this repo.
=> feat: allow plugins to modify the server and method map

lib/jsonwp-proxy/proxy.js
It looks like keeping these tokens creates internal memory leaks: https://github.com/appium/appium/issues/14693
=> fix: Disable request cancellation

lib/protocol/routes.js, test/protocol/routes-specs.js
https://github.com/appium/appium/issues/14719
=> feat: Add Webauthn routes

docs/mjsonwp/protocol-methods.md, lib/constants.js, lib/jsonwp-proxy/README.md, test/basedriver/driver-e2e-tests.js, test/basedriver/driver-tests.js, test/express/server-e2e-specs.js, test/jsonwp-proxy/proxy-specs.js, test/jsonwp-proxy/url-specs.js, test/protocol/protocol-e2e-specs.js, test/protocol/protocol-specs.js, test/protocol/routes-specs.js
https://github.com/appium/appium/projects/2#card-43906187
We want to remove `/wd/hub` default base path.
--
Haven't tested and tweaked well yet, but did the task intend to do like this? @jlipps 
(This PR is to 2.0 branch)
=> feat: Remove wd hub prefix

lib/basedriver/helpers.js, lib/express/idempotency.js, lib/protocol/protocol.js, package.json
=> chore: merge master to 2.0 branch

lib/express/idempotency.js
https://github.com/appium/appium-base-driver/pull/446
=> fix: Avoid unhandled error on driver exit

lib/express/idempotency.js
https://github.com/appium/appium-base-driver/pull/447 for 2.0 branch
=> fix: Avoid unhandled error on driver exit (#447)

lib/basedriver/driver.js, package.json, test/basedriver/driver-tests.js
This way we can always determine basedriver compatibility between appium server and drivers
=> feat: expose base driver version via inherited drivers

lib/express/server.js, test/express/server-e2e-specs.js, test/express/server-specs.js
this is plugin adjustment pr 3/3, i think it's the only one that doesn't depend on another one :-)
=> fix: update plugin server adjustment to use new style

lib/express/server.js, lib/protocol/protocol.js, test/express/server-e2e-specs.js, test/express/server-specs.js
basedriver shouldn't really know about plugins or drivers.
it should just expose the ability to update the server or add methods.
so let's get it out of here and move knowledge about drivers and plugins back to the main appium server where it belongs!
=> refactor!: generalize concepts of server updater and extra method map

.azure-pipelines.yml
=> ci: use node 12 and 14 instead of 10 and 12

lib/basedriver/commands/find.js, lib/basedriver/device-settings.js, package.json
Based on https://github.com/appium/appium-support/pull/222
=> feat: Add a setting to customize image matching method

README.md
=> chore(docs): point users to appium/appium for 2.x support

lib/basedriver/helpers.js, package.json
Based on https://github.com/appium/appium-support/pull/227
=> chore: Enable system unzip usage also in Windows by default

lib/basedriver/helpers.js
Related to https://github.com/appium/appium/issues/16050
=> feat: Make useSystemUnzip option configurable via process environment
